### ISSUE TITLE
The same subscription with different params remove the previous one

### ISSUE THREAD

**Issue by kl2karpenko** [samybob1/meteor-redux-middlewares#28]
After updating to version 3.0.7 my App was broken.
I have a couple of places one 1 page where I subscribe to the same entity like: 'entries.byParams' how it's said in docs

Example 
```
startSubscription({
     key:  'entries.byParams' ,
     get: () => { ..some code },
     subscribe: () => Meteor.subscribe(
             SUB_KEY,
              subsEntries
      ))
 })
```

My SUB_KEY is the same, but  subsEntries differs, and in version 3.0.6 I get updates for both of subscriptions (eg: ready: true comes to both of subscriptions), but in version 3.0.7 if I have 2 subscriptions with the same SUB_KEY, the previous one unsubscribe automaticaly after I subscribe to the second one with other params.

Can you please look If you can fix these?

**Comment by samylaumonier** [comment]
Hi @kl2karpenko, I'll have a look 😉

**Comment by samylaumonier** [comment]
Hi @kl2karpenko,

Version 3.0.7 was fixing issue #26. I think your issue is the same than #22. If you are using the same key for two subscriptions, how are we supposed to know which one we should stop when you dispatch `    dispatch(stopSubscription('entries.byParams'))`?

Would it be possible for you to use different keys for each subscription?

**Comment by linegel** [comment]
@samybob1 Looks like this issue could be closed :)
