### ISSUE TITLE
Need a way to stop subscriptions with an action when a component is destroyed

### ISSUE THREAD

**Issue by Koleok** [samybob1/meteor-redux-middlewares#4]
There is already some logic to stop subscriptions in the middleware, but only if a subscription action is dispatched that has been previously dispatched, presumably to keep things idempotent and support re-subscribing with new arguments.

There is also the scenario where you want to stop a subscription to avoid over-fetching after your app transitions to a new state, thus the motivation for previous patterns like [template level subscriptions](https://www.discovermeteor.com/blog/template-level-subscriptions/).

I have been playing around with how to do this in an elegant way, but I still haven't come up with something that feels right.

**Comment by samybob1** [comment]
Hi Kyle,

Indeed, it would be nice to be able to stop a subscription. One solution could be to add a `stopSubscription` action inside our package, that the user of the package can import and use.

This is what it could look like:
- [Compare the changes inside the package](https://github.com/samybob1/meteor-redux-middlewares/compare/stop-subscriptions?expand=1)
- [Compare the changes inside the demo](https://github.com/samybob1/meteor-redux-middlewares-demo/compare/stop-subscriptions?expand=1)

If you're ok, I can merge the branches and publish a new version of the package. Otherwise, you can make changes directly on the [stop-subscriptions](https://github.com/samybob1/meteor-redux-middlewares/tree/stop-subscriptions) branch.

Let me know if you have another ideas.

Thank you!

**Comment by Koleok** [comment]
This would work but it kind of violates the principle of a side-effect free action creator.

I'll just go ahead and experiment on this branch like you said to resolve that but I think otherwise exporting a _higher-order_ `stopSubscription` action creator is a good idea.

**Comment by samybob1** [comment]
You're right, maybe we can create an `unsubscribe` middleware that will intercept the unsubscribe actions sent from the `stopSubscription` action creator?

**Comment by Koleok** [comment]
Probably can just be another branch like you have it in `subscriptions` but we would just have a different predicate

**Comment by Koleok** [comment]
Ok well take a look at my fork on the [branch of the same name](https://github.com/Koleok/meteor-redux-middlewares/tree/stop-subscriptions/src)

This would constitute a breaking change to the API, so i am not sure how much production code you or anyone else has built on this, _(i am guessing not much since this was published a month ago ;) )_

You can now manually stop a subscription, but in order to make that process clean i did away with the user created action type and used types rather than action properties for control flow in the middleware. I opted for a generic `startSubscription` action that needs a `key` property used in the `subscriptions` look-up object.

The middleware still dispatches generated types based on the `key` prop passed with the initial `registerReactiveSource` or `startSubscription` actions.

**Comment by Koleok** [comment]
I made a fork of the demo that works with the new API check out the diff [here](https://github.com/samybob1/meteor-redux-middlewares-demo/compare/stop-subscriptions...Koleok:stop-subscriptions)

**Comment by samybob1** [comment]
Hi Kyle,

This is amazing! In the demo, I think we can put the key of the subscription (`home.posts`) in a constant.

Anyway, can you create the pull requests for the package and the demo? Then I'll merge it, update the README and publish the version 3 of the package. :tada: 

Thank you again!

**Comment by Koleok** [comment]
Sure thing i will put up the PRs, just going to make the exports a little better and I'll throw that constant in like you said.
